/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.fatec.View;

import br.gov.sp.fatec.Control.CadastroHospedeControl;
import br.gov.sp.fatec.Model.Hospede;
import br.gov.sp.fatec.ServicosTecnicos.Messages;
import br.gov.sp.fatec.ServicosTecnicos.TipoTelefoneEnum;
import java.awt.Component;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Thiago
 */
public class CadastroHospedeView extends javax.swing.JInternalFrame {
    private DefaultComboBoxModel<TipoTelefoneEnum> model;
    private CadastroHospedeControl control = new CadastroHospedeControl();
    private static CadastroHospedeView window;
    /**
     * Creates new form CadastroHospedeView
     */
    
    public static CadastroHospedeView getInstance() {
        if (window != null) {
            window.dispose();
            window = null;
        } 
        window = new CadastroHospedeView();
        ((BasicInternalFrameUI)window.getUI()).getNorthPane().remove(0);
        return window;
    }
    
    private CadastroHospedeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        dcNasc = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        cbTipoTel = new javax.swing.JComboBox<>();
        txtTelefone = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Hóspedes");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Cpf: ");

        jLabel3.setText("Telefone:");

        jLabel4.setText("E-Mail:");

        dcNasc.setDateFormatString("dd/MM/yyyy");

        jLabel5.setText("Data de nascimento: ");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        txtCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCpfMouseClicked(evt);
            }
        });
        txtCpf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCpfPropertyChange(evt);
            }
        });

        cbTipoTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoTelActionPerformed(evt);
            }
        });

        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefone.setEnabled(false);
        txtTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTipoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(dcNasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        preencherTipos();
        toggleState(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void cbTipoTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoTelActionPerformed
        if (cbTipoTel.getSelectedIndex() != -1) {
            txtTelefone.setEnabled(true);
            try {
                txtTelefone.setFormatterFactory(null);
                if (TipoTelefoneEnum.valueOf(cbTipoTel.getSelectedItem().toString()) == TipoTelefoneEnum.Celular)
                    txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
                else
                    txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
            } catch (ParseException ex) {
                Messages.showError("Erro de máscara: " + ex.getMessage());
            }
            txtTelefone.requestFocus();
        }
    }//GEN-LAST:event_cbTipoTelActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (!verificaCampos()) {
            Messages.showInformation("Preencha todos os campos!");
            return;
        }
        boolean result = control.adicionar(new Hospede(txtCpf.getText(), txtNome.getText(), txtTelefone.getText(), txtEmail.getText(), dcNasc.getDate()));
        if (result)
            Messages.showInformation("Hospede cadastrado!");
        else
            Messages.showError("Erro de cadastro");
        limparForm();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtCpfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCpfPropertyChange
        if (txtCpf.getText().contains(" "))
            return;
        Hospede temp = control.buscar(new Hospede(txtCpf.getText()));
        if (temp != null) {
            Messages.showError("Ja há um hospede vinculado a este Cpf");
            txtCpf.setText(null);
            toggleState(false);
        } else {
            toggleState(true);
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_txtCpfPropertyChange

    private void txtCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCpfMouseClicked
        txtCpf.setValue(null);
        txtCpf.setText(null);
        toggleState(false);
    }//GEN-LAST:event_txtCpfMouseClicked

    private void preencherTipos() {
        model = new DefaultComboBoxModel<>();
        for (TipoTelefoneEnum tipo : TipoTelefoneEnum.values()) {
            model.addElement(tipo);
        }
        cbTipoTel.setModel(model);
        cbTipoTel.setSelectedIndex(-1);
    }
    
    private void toggleState(boolean state) {
        txtNome.setEnabled(state);
        txtEmail.setEnabled(state);
        dcNasc.setEnabled(state);
        btnCadastrar.setEnabled(state);
        cbTipoTel.setEnabled(state);
        txtTelefone.setEnabled(false);
        if(state)
            getRootPane().setDefaultButton(btnCadastrar);
        else
            getRootPane().setDefaultButton(null);
    }

    private void limparForm() {
        for (Component component : getContentPane().getComponents()) {
            if (component instanceof javax.swing.JTextField)
                ((javax.swing.JTextField)component).setText(null);
            else if (component instanceof javax.swing.JComboBox)
                ((javax.swing.JComboBox)component).setSelectedIndex(-1);
            else if (component instanceof com.toedter.calendar.JDateChooser)
                ((com.toedter.calendar.JDateChooser)component).setDate(null);
        }
        toggleState(false);
        txtCpf.requestFocus();
    }
    
    private boolean verificaCampos() {
        for (Component component : getContentPane().getComponents()) {
            if (component instanceof javax.swing.JTextField && 
               ((javax.swing.JTextField)component).getText().length() == 0)
                return false;
            else if (component instanceof com.toedter.calendar.JDateChooser && 
                    ((com.toedter.calendar.JDateChooser)component).getDate() == null)
                return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<TipoTelefoneEnum> cbTipoTel;
    private com.toedter.calendar.JDateChooser dcNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
