/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.fatec.View;

import br.gov.sp.fatec.Control.ConsultaHospedeControl;
import br.gov.sp.fatec.Model.Hospede;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thiago
 */
public class ConsultaHospedeView extends javax.swing.JInternalFrame {
    private static ConsultaHospedeView window;
    /**
     * Creates new form ConsultaHospedeView
     */
    
    public static ConsultaHospedeView getInstance() {
        if (window != null) {
            window.dispose();
            window = null;
        } 
            window = new ConsultaHospedeView();
        return window;
    }
    
    private ConsultaHospedeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHospedes = new javax.swing.JTable();

        setClosable(true);
        setTitle("Consulta de Hóspedes");
        setFrameIcon(new ImageIcon(System.getProperty("user.dir") + File.separator +
            "images" + File.separator + "LogoSimple.png"));

    jLabel1.setText("Nome do Hóspede:");

    txtSearch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtSearchActionPerformed(evt);
        }
    });

    tbHospedes.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Id", "Cpf", "Nome", "Telefone", "DataNasc", "Email"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            true, false, false, false, true, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tbHospedes.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(tbHospedes);
    if (tbHospedes.getColumnModel().getColumnCount() > 0) {
        tbHospedes.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbHospedes.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbHospedes.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbHospedes.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbHospedes.getColumnModel().getColumn(4).setPreferredWidth(75);
        tbHospedes.getColumnModel().getColumn(5).setPreferredWidth(150);
    }

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSearch)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        ConsultaHospedeControl control = new ConsultaHospedeControl();
        List<Hospede> hospedes = control.pesquisa(txtSearch.getText());
        preencherTabela(hospedes);
    }//GEN-LAST:event_txtSearchActionPerformed

    private void preencherTabela(List<Hospede> hospedes) {
        DefaultTableModel model = (DefaultTableModel) tbHospedes.getModel();
        model.getDataVector().clear();
        Vector data;
        for (Hospede hospede : hospedes) {
            data = new Vector();
            data.add(hospede.getIdHospede());
            data.add(hospede.getCpf());
            data.add(hospede.getNome());
            data.add(hospede.getTelefone());
            data.add(new SimpleDateFormat("dd/MM/yyyy").format(hospede.getDataNasc()));
            data.add(hospede.getEmail());
            model.addRow(data);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHospedes;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
