/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.fatec.View;

import br.gov.sp.fatec.ServicosTecnicos.Messages;
import java.util.Date;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Thiago
 */
public class LocacaoView extends javax.swing.JInternalFrame {
    private static LocacaoView window;
    /**
     * Creates new form TestTable
     */
    
    public static LocacaoView getInstance() {
        if (window == null) {
            window = new LocacaoView();
            ((BasicInternalFrameUI)window.getUI()).getNorthPane().remove(0);
        } 
        return window;
    }
    
    private LocacaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLocRes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableLocacao = new javax.swing.JTable();

        setClosable(true);
        setTitle("Locação");
        setVisible(true);

        tableLocRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Quarto", "Tipo", "Check-In", "Check-Out"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, Date.class, Date.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLocRes.getTableHeader().setReorderingAllowed(false);
        tableLocRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLocResMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLocRes);

        jTabbedPane1.addTab("Locação por Reserva", jScrollPane1);

        tableLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableLocacao);

        jTabbedPane1.addTab("Locação", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencherReserva(){

    }
    
    private void tableLocResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLocResMouseClicked
        int row = tableLocRes.rowAtPoint(evt.getPoint());
        int col = tableLocRes.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 2) {
            if (col == 3){
                Object temp = tableLocRes.getValueAt(row, 2);
                if (temp == null) {
                    Messages.showInformation("Favor inserir data de check-in.");
                    return;
                }
                MainView.abreForm(new DatePick(tableLocRes, row, col, (Date)temp));
                return;
            }
            Object temp = tableLocRes.getValueAt(row, 3);
            if (temp != null)
                tableLocRes.setValueAt(null, row, 3);
            MainView.abreForm(DatePick.getInstance(tableLocRes, row, col));
        }
    }//GEN-LAST:event_tableLocResMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableLocRes;
    private javax.swing.JTable tableLocacao;
    // End of variables declaration//GEN-END:variables
}
