/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.fatec.View;

import br.gov.sp.fatec.ServicosTecnicos.Persistencia.ProdutoDAO;
import br.gov.sp.fatec.Model.ItemMenu;
import br.gov.sp.fatec.Model.Produto;
import br.gov.sp.fatec.ServicosTecnicos.Messages;
import java.awt.Point;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import java.util.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Thiago
 */
public class Test extends javax.swing.JInternalFrame {
    public static DefaultListModel<ItemMenu> model = new DefaultListModel<>();
    private static Test window;
    /**
     * Creates new form Test
     */
    
    public static Test getInstance() {
        if (window == null) {
            window = new Test();
            ((BasicInternalFrameUI)window.getUI()).getNorthPane().remove(0);
        }
        return window;
    }
    
    private Test() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannelProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_pedidos = new javax.swing.JList<>();

        setClosable(true);
        setTitle("Consumo");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pannelProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(list_pedidos);

        pannelProdutos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 492, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        model.clear();
        ProdutoDAO canal = new ProdutoDAO();
        List<Produto> produtos = new ArrayList<>();
        int offset = 10;
        try {
            produtos = canal.listar("");
        } catch (SQLException ex) {
            Messages.showError("Erro ao listar produtos: " + ex.getMessage());
        }
        for (Produto produto : produtos) {
            pannelProdutos.add(new ItemMenu(produto, new Point(offset, 20)), new org.netbeans.lib.awtextra.AbsoluteConstraints(offset, 20, -1, -1));
            offset += 80;
        }
        pannelProdutos.setComponentZOrder(jScrollPane1, pannelProdutos.getComponentCount() -1);
        list_pedidos.setModel(model);
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<ItemMenu> list_pedidos;
    private javax.swing.JPanel pannelProdutos;
    // End of variables declaration//GEN-END:variables
}
