/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.sp.fatec.View;
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Thiago
 */
public class TestMenuMouse extends javax.swing.JInternalFrame {
    private static TestMenuMouse window;
    /**
     * Creates new form TestMenuMouse
     */
    
    public static TestMenuMouse getInstance(java.awt.Point location) {
        if (window == null)
            window = new TestMenuMouse(location);
        return window;
    }
    
    private TestMenuMouse(java.awt.Point location) {
        initComponents();
        setOpaque(false);
        ((BasicInternalFrameUI)getUI()).setNorthPane(null);
        getContentPane().setBackground(new java.awt.Color(0,0,0,0));
        pack();
        setLocation(new java.awt.Point(location.x - (getWidth()/2), location.y - (getHeight()/2)));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProduto = new javax.swing.JButton();
        btnHospede = new javax.swing.JButton();
        btnQuitacao = new javax.swing.JButton();
        btnConsumo = new javax.swing.JButton();

        setBorder(null);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProduto.setText("Produto");
        btnProduto.setPreferredSize(new java.awt.Dimension(80, 80));
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 60));

        btnHospede.setText("Hóspede");
        btnHospede.setPreferredSize(new java.awt.Dimension(80, 80));
        btnHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospedeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 60));

        btnQuitacao.setText("Quitação");
        btnQuitacao.setPreferredSize(new java.awt.Dimension(80, 80));
        btnQuitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 60));

        btnConsumo.setText("Consumo");
        btnConsumo.setPreferredSize(new java.awt.Dimension(80, 80));
        btnConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospedeActionPerformed
        MainView.abreForm(CadastroHospedeView.getInstance());
    }//GEN-LAST:event_btnHospedeActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        MainView.abreForm(CadastroProdutoView.getInstance());
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumoActionPerformed
        MainView.abreForm(ProdutoView.getInstance());
    }//GEN-LAST:event_btnConsumoActionPerformed

    private void btnQuitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitacaoActionPerformed
        MainView.abreForm(PagamentoView.getInstance());
    }//GEN-LAST:event_btnQuitacaoActionPerformed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (compare(evt.getLocationOnScreen())) {
            MainView.removeForm(this);
            window = null;
        }
        
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsumo;
    private javax.swing.JButton btnHospede;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnQuitacao;
    // End of variables declaration//GEN-END:variables

    
    
    private boolean compare (java.awt.Point subject) {
        java.awt.Point p = getLocationOnScreen();
        return (subject.x < p.x || subject.y < p.y || 
                subject.x > (p.x + getWidth()) || subject.y > (p.y + getHeight()));
    }
}
